In [7]:
#!/usr/bin/python
# -*- coding:utf-8 -*-

import numpy as np

data = np.loadtxt('ex2data1.txt', delimiter=',')
print data.shape

X, y = np.split(data, (2, ), axis=1)
print y

(100L, 3L)
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


In [35]:
pos = y==1
neg = y==0
print len(y[pos])
x1 = X[:, 0].reshape(-1,1)
x2 = X[:, 1].reshape(-1,1)
plt.plot(x1[pos], x2[pos], 'k+', linewidth=4, markersize=7, label='Admitted')
plt.plot(x1[neg], x2[neg], 'yo', linewidth=4, markersize=6, label='Not admitted')
plt.xlabel('Exam 1 score')
plt.ylabel('Exam 2 score')
plt.title('Final Results')
# plt.legend(loc='upper left')
plt.legend(loc='upper right')
plt.show()

60


In [37]:
# Plotting

import matplotlib as mpl
import matplotlib.pyplot as plt
print 'Plotting data with + indicating (y = 1) examples and o '\
'indicating (y = 0) examples.\n'

def plotData(X, y):
    pos = y==1
    neg = y==0
#     print len(y[pos])
    x1 = X[:, 0].reshape(-1,1)
    x2 = X[:, 1].reshape(-1,1)
    plt.plot(x1[pos], x2[pos], 'k+', linewidth=4, markersize=7, label='Admitted')
    plt.plot(x1[neg], x2[neg], 'yo', linewidth=4, markersize=6, label='Not admitted')
    plt.xlabel('Exam 1 score')
    plt.ylabel('Exam 2 score')
    plt.title('Final Results')
    # plt.legend(loc='upper left')
    plt.legend(loc='upper right')
    plt.show()

plotData(X, y)

Plotting data with + indicating (y = 1) examples and o indicating (y = 0) examples.

60


In [196]:
def sigmoid(Z):
    expz = np.exp(-Z)
    sigmd = 1/(1+expz)
    return sigmd

def costFunction(X, y, theta):
    m = len(y)
    hx = sigmoid(np.dot(X, theta))
    print hx.shape
    j = -1*np.dot(y.T, np.log(hx)) - np.dot((1-y.T), np.log(1-hx))
    j=j/m
#     grad = np.dot(X.T, (hx-y))/m
    return j[0][0]

def costFunction2(X, y, theta):
    m = len(y)
#     print np.dot(X, theta)
    hx = sigmoid(np.dot(X, theta))
#     print hx
#     print hx.shape
    j = -1*np.dot(y.T, np.log(hx)) - np.dot((1-y.T), np.log(1-hx))
    j=j/m
    # grad = X'.(hx-y)/m
    grad = np.dot(X.T, (hx-y))/m
    return j[0][0], grad
    
(m, n)=X.shape
print m, n
Xt = np.hstack((np.ones((m, 1)), X))
initial_theta = np.zeros((n+1, 1))
cost= costFunction(Xt, y, initial_theta)
print cost
theta = initial_theta
# cost,grad = costFunction2(Xt, y, initial_theta)
# print cost, grad

100 2
(100L, 1L)
0.69314718056


In [211]:
# 直接使用梯度下降，收敛非常慢，需要更高级的优化算法
alpha=0.005
for i in range(1000000):
    j, delta=costFunction2(Xt, y, theta)
#     print j, delta
    theta = theta - alpha*delta
print j
print theta

0.237358524737
[[-29.9957439 ]
 [  0.25565616]
 [  0.24972642]]


In [217]:
# 直接使用梯度下降，收敛非常慢，需要更高级的优化算法
# 迭代次数10,000,000，一千万次，勉强收敛到一个比较好的值
def gradientDescent(X, y, theta, alpha, costfunc, iterations):
    m = len(y)
    j_history = np.zeros((iterations, 1))

    for iter in range(iterations):
        j_history[iter], delta = costfunc(X, y, theta)
        theta = theta - alpha*delta

    # plt.plot(j_history, 'b-', linewidth=4)
    # plt.show()
    print j_history

    return theta

theta = gradientDescent(Xt, y, theta, 0.001, costFunction2, 10000000)
print theta

[[ 0.20352489]
 [ 0.20352489]
 [ 0.20352489]
 ..., 
 [ 0.20352472]
 [ 0.20352472]
 [ 0.20352472]]
[[-24.73813787]
 [  0.20284681]
 [  0.1980472 ]]


In [232]:
theta = gradientDescent(Xt, y, theta, 0.003, costFunction2, 10000000)
print theta

[[ 0.20350725]
 [ 0.20350725]
 [ 0.20350725]
 ..., 
 [ 0.2034977 ]
 [ 0.2034977 ]
 [ 0.2034977 ]]
[[-25.16130031]
 [  0.20623145]
 [  0.20147133]]


In [238]:
# 预测
def predict(X, theta):
    m = len(X)
    p = sigmoid(np.dot(X, theta))
    return p
prob = sigmoid(np.dot(np.array([1, 45, 85]), theta))
print 'For a student with scores 45 and 85, we predict an admission ', 'probability of %f\n' % prob

# 计算训练准确率
p = predict(Xt, theta)
p_r = p>=0.5
# print p_r
accuracy = np.mean(p_r==y)
print 'accuracy: %0.2f%%\n' % (accuracy*100)

For a student with scores 45 and 85, we predict an admission  probability of 0.776290


accuracy: 89.00%



In [65]:
import scipy.optimize as opt
a = opt.fmin(costFunction(Xt, y, initial_theta), 5)
# theta=initial_theta
# j, delta=costFunction2(Xt, y, theta)
# print j, delta
# theta = theta - delta
print a

(100L, 1L)


TypeError: 'numpy.float64' object is not callable

In [97]:
A = np.array([[-31, -10, -3, 1,3,4], [-31, -10, -3, 1,3,4]])
sigm = sigmoid(A)
print sigm,sigm.shape
print A>0
print A[A>0]
np.log(A[A>0])

[[  3.44247711e-14   4.53978687e-05   4.74258732e-02   7.31058579e-01
    9.52574127e-01   9.82013790e-01]
 [  3.44247711e-14   4.53978687e-05   4.74258732e-02   7.31058579e-01
    9.52574127e-01   9.82013790e-01]] (2L, 6L)
[[False False False  True  True  True]
 [False False False  True  True  True]]
[1 3 4 1 3 4]


array([ 0.        ,  1.09861229,  1.38629436,  0.        ,  1.09861229,
        1.38629436])